### ISSUE TITLE
Color Scheme Chooser

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-pantheon-shell#215]
We need to come up with an interface for the prefers-color-scheme setting.

We should bear in mind that this setting has 3 states: prefer `dark`, prefer `light`, and `no-preference` (maybe we can call this mixed or automatic or something more palatable). It seems like most major platforms only handle `no-preference` and `dark`.

I think we want to do a slow rollout and start with only shell elements, so the first version of this should probably be two illustrations depicting light shell elements and dark shell elements. By shell elements I mean the dock and panel popovers.

It might be worth depicting mixed windows so that the user knows this only changes shell elements and not apps.

Future versions of this selector should probably be three illustatrations:
* One with light shell elements and app windows
* One with light shell elements and mixed app windows
* One with dark shell elements and dark app windows

**Comment by cassidyjames** [comment]
We also don’t _have_ to expose a light preference if we don't want to. :slightly_smiling_face: But I don't feel strongly, I guess it would probably be what some people immediately ask for.

**Comment by danrabbit** [comment]
Prior art from:

## macOS
![macos-dark-mode](https://user-images.githubusercontent.com/7277719/79782534-2275d480-82f4-11ea-9a99-1e6ff2f0f2a5.jpg)

## iOS
![darkmodeschedules](https://user-images.githubusercontent.com/7277719/79782554-299ce280-82f4-11ea-917b-20fca9e2dc23.jpg)

## Ubuntu
![dark-theme-settings-ubuntu-thumbnail-sized](https://user-images.githubusercontent.com/7277719/79782575-2efa2d00-82f4-11ea-9e28-b5b4e0085f7c.jpg)

**Comment by cassidyjames** [comment]
@danrabbit do we want to include agent dialogs as shell components? I feel like yes, but that could also come later.

I like the idea of showing mixed apps. Super rough whiteboard sketch:

![IMG_20200420_114659](https://user-images.githubusercontent.com/611168/79782832-ed21b480-82fc-11ea-9752-f790a2b9b301.jpg)

**Comment by danrabbit** [comment]
@cassidyjames Yeah I'm not sure at this size that it would be clear the difference between an agent and an app window

**Comment by cassidyjames** [comment]
Oops, top window was supposed to be dark. Yeah, don't need to distinguish agents at this size.

**Comment by danrabbit** [comment]
Regarding the setting name, I think even if we only expose two settings we should avoid "Light" since that's not really true. And thinking about it, "automatic" could be confused for time-based. So maybe "Mixed" and "Dark"?

**Comment by cassidyjames** [comment]
Yeah defintely want to avoid "light" for a binary choice. That's why in the switch-bassed prototype #171 I just had it something like "prefer dark style" with descriptive text below. I don't know what that means for an illustration, though. 

![screenshot](https://user-images.githubusercontent.com/611168/54170914-2cb17800-443e-11e9-8a45-742c25bbe719.png)

"Mixed" feels weird to me, too. Maybe just "Default"? But I feel like no matter what we do, we're gonna want some descriptive text.

**Comment by cassidyjames** [comment]
Terrible, bad UI from Android incoming. I think this is because they kind of bolted this feature on mid-cycle. But just for prior art completeness sake (and maybe an exercise in what not to do…)

| ![Screenshot_20200420-115256](https://user-images.githubusercontent.com/611168/79783748-5a821500-82fe-11ea-8198-dc24f11db0fc.png) | ![Screenshot_20200420-115301](https://user-images.githubusercontent.com/611168/79783754-5e159c00-82fe-11ea-99e0-68a37c269d34.png) |
|---|---|
| ![Screenshot_20200420-115318](https://user-images.githubusercontent.com/611168/79783784-6c63b800-82fe-11ea-8af4-cfae0e20b896.png) | ![Screenshot_20200420-115318](https://user-images.githubusercontent.com/611168/79783798-72f22f80-82fe-11ea-9a01-135957a26650.png) |
| ![Screenshot_20200420-115243](https://user-images.githubusercontent.com/611168/79783810-7be30100-82fe-11ea-8ca1-f0c8303674c6.png) | ![Screenshot_20200420-115247](https://user-images.githubusercontent.com/611168/79783831-84d3d280-82fe-11ea-9a28-dd1f15a17725.png)
