### ISSUE TITLE
More granular text DPI scale

### ISSUE THREAD

**Issue by hanaral** [elementary/switchboard-plug-pantheon-shell#248]
The current scale of small, default, large and XL is not enough for most displays, and even I find myself using dconf to change my text DPI 100% of the time.
I think that an iOS styled sanity-checked scale would be less overkill compared to users using 'Large' when they realistically only need 5% adjustment.

**Comment by danrabbit** [comment]
I wouldn't be opposed to using a scale here instead of buttons. I'm not sure that there's a compelling reason to have specific sizes

**Comment by hanaral** [comment]
> I wouldn't be opposed to using a scale here instead of buttons. I'm not sure that there's a compelling reason to have specific sizes

I'd still prefer there to be a sane maximum and minimum, since I'm certain that anything higher than XL should be under the UI scaling (If you are still working on the one demonstated on twitter before)

**Comment by danrabbit** [comment]
Yeah, since anything at integer values would use display scaling instead of text scaling, the scale should definitely be no smaller than 0.6 and no greater than 1.9 at extremes. The current "Small" is `0.75` and "Larger" is `1.5`. I imagine we could just keep these bounds, but use a scale instead of buttons for more granular control

**Comment by cassidyjames** [comment]
Yeah the other thing to consider is that 0.75@2x and 1.5@1x are where the font size and scale factors overlap, which is why those are the current bounds. 

I think we chose specific sizes instead of a scale in the past so people didn't just tweak on it a little and end up with everything looking wonky, but that was before the stylesheet handled text sizing like it does now.

**Comment by casasfernando** [comment]
I totally support this feature.
I'm a loyal, long time elementary OS user and I recently got a Dell XPS 13 with 4K display.
While testing Odin, I found that the Default value for text scaling is a bit small, while the next available size, Large, is a bit to large.
Looking at the source code I found the gsettings key to tweak and now I'm running on 1.125 which I found it's perfect in my case.

Having said that, it would be ideal to have a slider instead of buttons with reasonable steps (certainly more than 4) to set the text scaling factor and have more granularity.
